import { Html, Head, Main, NextScript } from 'next/document'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Musicle',
  description: 'Generated by create next app',
}

export default function Document() {
  return (
    <Html>
      <Head>
        <title>Musicle</title>
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}